from _typeshed import Incomplete

listen_s: Incomplete
client_s: Incomplete
DEBUG: int

def connect_wifi(ssid, password, timeout: int = 15) -> None: ...
def server_handshake(cl): ...
def send_html(cl) -> None: ...
def setup_conn(port, accept_handler): ...
def accept_conn(listen_sock): ...
def stop() -> None: ...
def start(port: int = 8266, password=None, accept_handler=...) -> None: ...
def start_foreground(port: int = 8266, password=None) -> None: ...
