from _typeshed import Incomplete

def on_connect() -> None: ...

timer_hb: Incomplete
client_s: Incomplete
_url: Incomplete
_uid: Incomplete
_default_url: str
_config_file: str
_uid_key: str
ssl_ctx: Incomplete

def connect_wifi(ssid, password, timeout: int = 15) -> None: ...
def _curious_base24(n, length): ...
def _format_uid(num): ...
def _get_stable_uid():
    """Return a stable UID derived from machine.unique_id(), if available."""
def _get_random_uid():
    """Generate a random UID"""
def _get_stored_uid():
    """Random UID stored it in the config file."""
def _hbeat(tmr) -> None: ...
def _start(uid=None, url=...) -> None: ...
def start(uid=None, url=...) -> None: ...
def stop() -> None: ...
def started(): ...
