import io
from _typeshed import Incomplete

_MP_STREAM_POLL: Incomplete
_MP_STREAM_POLL_RD: Incomplete
_timer: Incomplete

def schedule_in(handler, delay_ms) -> None: ...

class BLEUARTStream(io.IOBase):
    _uart: Incomplete
    _tx_buf: Incomplete
    def __init__(self, uart) -> None: ...
    def _on_rx(self) -> None: ...
    def read(self, sz=None): ...
    def readinto(self, buf): ...
    def ioctl(self, op, arg): ...
    def _flush(self) -> None: ...
    def write(self, buf) -> None: ...

def start() -> None: ...
